spring:
  application:
    name: template
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
  security:
    jwt:
      secret: 4c57f5bce709474cda66f67778ade103f84c81458cd98d33ad76e960f520462e
      expiration: 3600000

